server:
  port: 8090

spring:
  application:
    name:   USER-SERVICE

  eureka:
    instance:
      hostname: localhost
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/